### ISSUE TITLE
Backups don't need to be skipped for dev while in SFTP

### ISSUE THREAD

**Issue by bmackinney** [uberhacker/pantheon-backup#1]
Consider expanding the logic used to skip backups for dev/multidev environments due to being in SFTP mode. If [`terminus site code diffstat`](https://github.com/pantheon-systems/cli/blob/93d6a35e6ef7d3ac9f25934aa40b7aa084937d4d/php/Terminus/Commands/SiteCommand.php#L319) returns "no changes on server", the code backup will be in sync with the database at that point in time. If it returns data, consider committing with `terminus site code commit --message="Automatic backup commit"`.

**Comment by uberhacker** [comment]
Thanks for the feedback Brian.  I actually do have some logic that checks if the site is not in git mode and skips those environments.  But the database sync check is a great consideration.  Do you know the best way to check if environments have been created?  Currently, I'm just assuming that if the mode is not set, it must mean the environment has not been created yet.

**Comment by bmackinney** [comment]
Right. That's the logic I'm commenting on above, suggesting you don't need to skip them. git mode is only required for restoring from a backup. Creating a backup in sftp mode only gets users into trouble if there are commits pending, because it takes a backup of the repository, not the filesystem directory. 

We have logic in our documentation deploy script that writes terminus environments to a file
https://github.com/pantheon-systems/documentation/blob/master/scripts/deploy-multidev.sh#L25

**Comment by uberhacker** [comment]
I have some reservations about performing an "automatic backup commit" because we probably shouldn't assume the user actually wants to commit the changes in sftp mode.  I like the idea of making sure the user is aware that the repository and filesystem might be out of sync and prompting them whether they want to commit their changes before performing the backup.  The only problem with that approach is that you would need the option to have the script answer the prompt silently if there is a cron job.  In that case, the "automatic backup commit" makes sense.

**Comment by bmackinney** [comment]
yeah that could be a commented out option that users could enable globally or not by removing the comment. If the diffstat command returns data, then you could skip the backup.

**Comment by uberhacker** [comment]
Am I correct in assuming if the connection mode is not set, that means the environment has not been created yet or is there a better way to check?  What do you think about a "-f" option that forces a backup in sftp mode if the diffstat returns results?  I'm thinking in those cases, we would need to switch from sftp to git mode, commit the changes and then switch back to sftp mode.  Is this a correct assessment?

**Comment by bmackinney** [comment]
If diffstat returns results, they will not be included in a backup until committed. 
in this case, that's when you'd want to either commit them or skip the backup to avoid code/db sync issues.

Does terminus code backup fail if in SFTP mode? it should not. The dashboard allows you to create a backup if in SFTP mode, and only warns you to commit any changed/uncommitted files if you are in SFTP mode. You should therefore not have to switch the connection mode to git to create a backup in terminus. Switching connection mode is only necessary to restore from a backup.

**Comment by uberhacker** [comment]
I get that but I'm talking about when you do the "automatic backup commit".  You have to be in git mode in order to do that, correct?

**Comment by bmackinney** [comment]
No. On server commits are done in SFTP mode. if the `terminus site code diffastat` command returns data, it means there are changes to commit. At that point your script could either skip the backup or run `terminus site code commit --message="automatic backup commit"` to commit it before creating the backup, which would then include the code that was running but uncommitted. No need to switch modes.

**Comment by uberhacker** [comment]
Gotcha, that makes sense.  I'll try and implement the proposed change soon.

**Comment by uberhacker** [comment]
Brian,
Please look over the latest commit when you get a chance to see if the automatic backup commit logic looks like what you had suggested.
Thanks

**Comment by bmackinney** [comment]
:+1: LGTM. Let me know when you have a chance to see it in action!

**Comment by uberhacker** [comment]
Hey Brian,
I have tested it several times with different scenarios and it works fine.  I was hoping you could check it out also and let me know what you think.  Ronan asked me if I wanted to port it to a Terminus plugin.  What do you think?

**Comment by bmackinney** [comment]
can you email me the site dashboard URL you're testing against? I think making it a plugin is a cool idea, if you have the time to do it.
